serverId: ""
hashKey: ""

chatFormat:
  from_game: "<{name}> {msg}"
  from_group: "群:<{nick}> {msg}"
  post_chat: true
  post_prefix: ""

motd:
  server_ip: "play.easecation.net"
  server_port: 19132
  api: "https://motdbe.blackbe.work/status_img?host={server_ip}:{server_port}"
  text: "共{online}人在线"
  output_online_list: true
  post_img: true

customCommand:
  - key: "加白名"
    command: "whitelist add &1"
    permission: 0
  - key: "管理加白名"
    command: "whitelist add &1"
    permission: 1

version: 2
